# Generated by Django 6.0.1 on 2026-01-17 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_descontado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
