# Generated by Django 6.0.1 on 2026-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('unissex', 'Unissex')], default='Unissex', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(choices=[('oboticario', 'OBoticario'), ('natura', 'Natura'), ('eudora', 'Eudora'), ('blossom', 'Blossom')], default='Não especificado', max_length=10),
        ),
    ]
