# Generated by Django 6.0.1 on 2026-01-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_genero_alter_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('perfume', 'Perfume'), ('sabonete', 'Sabonete'), ('hidratante', 'Hidratante')], default='perfume', max_length=20),
        ),
    ]
